version: '3.4'

services:
  poker:
    image: easy-poker:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    command: 'start'
